# Chapter 1. 신경망 복습

## 수학과 파이썬 복습

In [1]:
import numpy as np

In [25]:
# 벡터와 행렬
x = np.array([1,2,3])
print(x.__class__) # 클래스 이름 
print(x.shape) # 원소 수가 3개 벡터
print(x.ndim) # 1차원 배열
print()
W = np.array([[1,2,3],[4,5,6]])
print(W.shape) # 2X3 행렬
print(W.ndim) # 2차원 배열

<class 'numpy.ndarray'>
(3,)
1

(2, 3)
2


In [20]:
# 행렬의 원소별 연산
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
display(W+X)
display(W*X) 

array([[ 1,  3,  5],
       [ 7,  9, 11]])

array([[ 0,  2,  6],
       [12, 20, 30]])

numpy 연산 ; 원소 별로 연산이 이루어짐. 행과 열 개수 맞지 않아도 okay.

In [22]:
# 브로드캐스트
A = np.array([[1,2],[3,4]])
display(A*10) 

A = np.array([[1,2],[3,4]])
b = np.array([10,20])
display(A*b) 

array([[10, 20],
       [30, 40]])

array([[10, 40],
       [30, 80]])

1. 벡터와 스칼라 간의 연산이 가능하다.
2. 1차원과 2차원 간의 연산이 가능하다.

In [27]:
# 벡터의 내적과 행렬의 곱

# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
display(np.dot(a,b)) # dot product

# 행렬의 곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
display(np.dot(A,B))
display(np.matmul(A,B)) # matrix multiply

32

array([[19, 22],
       [43, 50]])

array([[19, 22],
       [43, 50]])

np.dot은 1차원 배열이면 벡터 내적 계산, 2차원 배열이면 행렬의 곱을 계산한다. 즉, np.matmul의 기능도 있음. 

하지만 **코드의 논리와 의도를 명확히 하기 위해 둘을 분리** 해주는 것이 좋음

`numpy 연습해보기`

- http://www.labri.fr/perso/nrougier/from-python-to-numpy
- https://github.com/rougier/nu%E3%85%81mpy-100

## 신경망의 추론

In [36]:
def sigmoid(x): # 활성화 함수
    return 1/(1 + np.exp(-x))

x = np.random.randn(10,2) # 입력. 10개의 샘플데이터.
display(x.shape)
W1 =np.random.randn(2,4) # 가중치 # 4개
b1 = np.random.randn(4) # 편향
W2 =np.random.randn(4,3) # 가중치
b2 = np.random.randn(3) # 편향

h = np.matmul(x,W1) + b1
display(h.shape)
a = sigmoid(h)
s = np.matmul(a,W2) + b2
display(s.shape)

(10, 2)

(10, 4)

(10, 3)

x의 형상은 (10,2). 이는 2차원 데이터 10개가 미니배치로 처리된다는 뜻이다. 그리고 최종 출력인 s의 shape는 (10,3)이 된다. 이것은 10개의 데이터가 한꺼번에 처리되었고, 각 데이터는 3차원으로 변환되었다는 것을 의미한다. 3차원 데이터의 값을 이용한다면 3 클래스 분류를 할 수 있다. 각 차원은 각 클래스에 해당하는 점수가 되며 가장 큰 값이 분류 예측 결과가 되는 것이다.

* `x[0]`은 0번째 입력 데이터, `x[1]`은 1번째 입력 데이터, `h[0]`은 0번째 데이터의 은닉층 뉴런, `h[1]`은 1번째 데이터의 은닉층 뉴런.

* 활성화 함수인 시그모이드 함수는 선형함수를 비선형 함수로 변환해서 출력해줌